name: python3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          cd python3
          PYTHONPATH=.. python3 test.py
      - name: Try sample
        run: |
          cd python3
          cat ../data/sample.txt | python3 revert.py
